blog/blog/urls.py
from typing import Any
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns: list[Any] = [
    path(route='admin/', view=admin.site.urls),
    path(route='', view=include(arg='blogapp.urls')),
    path(route='accounts/', view=include(arg='accounts.urls', namespace='accounts')),
] + static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blogapp/models.py

# Create your models here.
# blog/models.py
from django.db import models
from accounts.models import CustomUser
from django.urls import reverse
from django.utils import timezone



class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    content = models.TextField()
    image = models.ImageField(upload_to='post_images/', null=True, blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, \
                                            related_name='blog_posts')
    objects = models.Manager()


    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.pk)])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    
    class Meta:
        ordering = ['-created_at']
        
    def __str__(self):
        return f"{self.author.username} - {self.content[:50]}"

class Rating(models.Model):
    CHOICES=[
        (1, '1'), 
        (2, '2'),
        (3, '3'), 
        (4, '4'),
        (5, '5'), 
        ]
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='ratings')
    value = models.IntegerField( choices=CHOICES)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-post']

    def __str__(self):
        return f'{self.author.username} - {self.value}'

blog/blogapp/forms.py
# blog/forms.py
from django import forms
from .models import Post, Comment, Rating


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields: list[str] = ['title', 'content', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields: list[str] = ['content']


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields: list[str] = ['value']


class SearchForm(forms.Form):
    query = forms.CharField(required=False)

blog/templates/blog/comment_create.html
<!-- blog/templates/blog/comment_create.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Add a Comment</h2>
  {% if post.pk %}{{ post.pk }}{% else %}No post.pk value{% endif %}
  {# Temporary debug statement to print the URL #}
{% url 'rate_post' pk=post.pk as rate_post_url %}
<p>Debug: Rate Post URL: {{ rate_post_url }}</p>
  <form method="post" action="{% url 'comment_create' pk=post.pk %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Comment</button>
  </form>
{% endblock %}

blog/templates/blog/post_create.html
<!-- blog/templates/blog/post_create.html -->
{% extends 'base.html' %}

{% block content %}
<div class="flex justify-center items-center max-w-full">
<div class="max-w-md flex flex-col items-center bg-gray-100">
  <div class="text-xl py-2 w-full my-3 bg-indigo-600 text-white text-center">Create a New Post</div>
  <div class="pl-5">
  <form method="post" enctype="multipart/form-data" action="{% url 'post_create' %}">
    {% csrf_token %}
    <div class="flex-col mb-2">
      <label for="title" class="block mb-2 text-sm ">{{form.title.label}}</label>
          <p >
            <style>
              #id_title {
                  /* Add your desired styles here */
                  padding: 5px;
                  /* background-color: #010f16;  Blue background color */
                  /*color: #fff; White text color */
                  width:400px;
                  border-style: solid;
                  border-width: 2px;
                  border-color: black;
                  border-radius: 10px;
              }
          </style>
            {{form.title}}</p>
    </div>
    <div class="flex-col mb-2">
      <label for="username" class="block mb-2 text-sm ">{{form.content.label}}</label>
          <p class="rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white placeholder-gray-900 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500">
            <style>
              #id_content {
                  /* Add your desired styles here */
                  padding: 5px;
                  /* background-color: #010f16;  Blue background color */
                  /*color: #fff; White text color */
                  width:400px;
                  border-style: solid;
                  border-width: 2px;
                  border-color: black;
                  border-radius: 10px;
              }
          </style>
            {{form.content}}</p>
    </div>
   
    <br>
    {{form.image.label}}
    {{form.image}}
    <div>
    <button type="submit" class="bg-indigo-600 text-white w-full my-6 py-2 rounded-lg ">Create Post</button>
  </div>
    </form>
  </div>
</div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
<!-- blog/templates/blog/post_detail.html -->
{% extends 'base.html' %}
{%load static%}
{% block content %}
<div class="flex justify-arround ">
  <div class="w-1/3 m-2">
    {% if post.image %}
    <img src="{{ post.image.url }}" alt="{{ post.title }}" class=" w-full h-96 hover:opacity-80 hover:scale-125">
    {% endif %}
  </div>
  <div class="w-2/3 m-2 ">
    <h2 class="bg-indigo-700 text-white text-xl text-center py-2 ">{{ post.title }}</h2>
    <p class="">{{ post.content }}</p>

    <p class="bg-gray-700 text-white pl-2 w-1/2">Posted by {{ post.author.username }} on {{ post.created_at }}</p>
  </div>
  
</div>
<div class="flex  max-w-full">

  <div class="bg-black w-1/3 m-2">
    <!-- Display comments -->
    <h3 class="text-center bg-indigo-900 text-white text-lg py-3 mb-2">Comments ({{ comments.count }})</h3>
    {% for comment in comments %}
    <p class="text-white"><span class="bg-red-700  px-2 py-1 ">{{ comment.author.username }} said:</span>
       {{comment.content }} ({{ comment.created_at }})</p>

    {% endfor %}
  </div>

  <div class="bg-gray-200 w-1/3 m-2">

    <!-- Comment form -->
    <h2 class="text-center bg-indigo-900 text-white text-lg py-3">Add a Comment</h2>
    <form method="post" action="{% url 'post_detail' pk=post.pk %}">
      {% csrf_token %}
      {{comment_form.content.label}}
      <br>
      <p>
        <style>
          #id_content {
            /* Add your desired styles here */
            padding: 5px;
            margin-left: 2px;
            margin-right: 2px;
            /* White text color */
            width: 421px;
            border-style: solid;
            border-width: 2px;
            border-color: black;
            border-radius: 10px;
          }
        </style>
        {{comment_form.content}}
      </p>


      <button type="submit" class="w-full bg-blue-700 text-white py-2 px-3 hover:bg-blue-500">Submit Comment</button>
    </form>

  </div>
  <div class="bg-gray-200 w-1/3 m-2">
    <h2 class="text-center bg-indigo-900 text-white text-lg py-3">Add Ratings</h2>
    <div class="flex justify-arround my-2">
      <div class="w-1/2">
        <!-- Display ratings -->
        {% for rating in ratings %}
        <span class="px-2 py-1">
          {{ rating.author.username }} rated:</span> {{ rating.value }}<br>
        {% endfor %}
      </div>
      <div class="w-1/2">
        <!-- Rating form -->
        <form method="post" action="{% url 'post_detail' pk=post.pk %}">
          {% csrf_token %}
          <div class="p-2">
            {{rating_form.value.label}}
            <div class="flex">
              <span>
                {{ rating_form.value }}
                <style>
                  #id_value {
                    width: 50px;
                    text-align: center;
                  }
                </style>
              </span>
            </div>
          </div>
          <div class="p-2">
            <button type="submit" class="bg-blue-700 w-full text-white py-2 px-3 hover:bg-blue-800">Submit
              Rating</button>
          </div>
        </form>
        <div>
          <img src="{%static 'img/developer.jpg'%}" alt="">
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
<!-- blog/templates/blog/post_list.html -->
{% extends 'base.html' %}

{% block content %}


<div class="flex-col mt-5">
  <div class="">

    <script>
      const text = "🐍Welcome to my portfolio. I am a passionate developer of python django 🔥!";
      let index = 0;
      const speed = 100; // Adjust typing speed here

      function typeWriter() {
        if (index < text.length) {
          document.getElementById("typewriter").innerHTML += text.charAt(index);
          index++;
          setTimeout(typeWriter, speed);
        }
      }
    </script>
    <div id="typewriter" class="text-3xl font-bold text-center"></div>
    <script>typeWriter();</script>
  </div>
  <div class="flex my-2">
    <div class="w-1/4 flex justify-center">
      <a href="{%url 'post_create'%}" class="bg-green-500 text-white text-center py-2 rounded-md w-64 ">Create Post</a>
    </div>
    <div class="w-3/4">
      <h2 class="text-center text-2xl font-bold py-2">Blog Posts</h2>
    </div>
  </div>
  {% for post in posts %}
  <div class="post flex justify-arround py-2">
    <div class="w-1/4 ">
      {% if post.image %}
      <img src="{{ post.image.url }}" width="300" alt="{{ post.title }}" class="ml-4 h-96">
      {% endif %}
    </div>
    <div class="w-3/4 mx-2 ">
      <h3 class="text-xl bg-indigo-700 text-white py-3 text-center">{{ post.title }}</h3>
      <div class="flex-col justify-between p-2">
        <div>{{ post.content }}</div>
        <div class="flex justify-between items-center">
          <p class="font-semibold mt-8 py-1">Posted by {{ post.author.username }} on {{ post.created_at }}</p>
          <a href="{% url 'post_detail' pk=post.pk %} " class="text-indigo-700 font-bold float-right ">Read more</a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}

  <!-- Pagination -->
  <div class="pagination text-center my-5">
    <span class="step-links">
      {% if posts.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ posts.previous_page_number }}">previous</a>
      {% endif %}
      <span class="current">
        Page <span class="font-semibold px-3 border border-3 border-black">{{ posts.number }}</span> of <span
          class="font-semibold px-3 border border-3 border-black"> {{ posts.paginator.num_pages }}</span>
        {% if posts.has_next %}
        <a href="?page={{ posts.next_page_number }}">next</a>
        <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
  </div>
</div>
{% endblock %}

blog/templates/blog/rate_post.html
<!-- blog/templates/blog/rate_post.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Rate this Post</h2>
  {% if post.pk %}{{ post.pk }}{% else %}No post.pk value{% endif %}
  {# Temporary debug statement to print the URL #}
{% url 'rate_post' pk=post.pk as rate_post_url %}
<p>Debug: Rate Post URL: {{ rate_post_url }}</p>
  <form method="post" action="{% url 'rate_post' pk=post.pk %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="bg-blue-500 text-white">Submit Rating</button>
  </form>
{% endblock %}

blog/templates/blog/search.html
{% extends "base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
<div class="flex justify-center items-center mt-8">
  <div class="w-full lg:w-3/4">
    {% if query %}
    <p>Posts containing :<span class="font-bold"> {{ query }}</span></p>
    <h3 class="font-semibold text-xl">
      {% with results.count as total_results %}
      Found :{{ total_results }}
      <br>
      result :{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
    <h4 class="font-bold">
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h4>
    {{ post.content|truncatewords_html:12 }}
    {% empty %}
    <p>There are no results for your query.</p>
    {% endfor %}
    <a href="{% url 'search' %}"
        class="block w-1/2 my-3 py-2 rounded-lg bg-green-500 text-white text-center font-semibold hover:bg-green-600 hover:cursor-pointer">Search
        again</a>
    {% else %}

    <form method="get" class="space-y-4">
      <h1 class="blink bg-red-500 text-white text-xl text-center my-2 py-1">Search for posts</h1>
      {{ form.as_p }}
      <style>
        #id_query {
          width: 250px;
          height: 35px;
          border: 1px solid black;
          border-radius: 5px;
          margin-top: 20px;
          padding-left: 3px;

        }
      </style>
      <input type="submit" value="Search"
        class="w-full bg-green-500 text-white text-xl text-center my-2 py-1 hover:bg-green-600 hover:cursor-pointer">

    </form>
    {% endif %}
  </div>
</div>
{% endblock %}